### ISSUE TITLE
Call to undefined method aharen\Language\LanguageServiceProvider::validate()

### ISSUE THREAD

**Issue by DesmondLouis** [aharen/Language#1]
Directly after the install i got this problem thanks for any help

**Comment by aharen** [comment]
Hi @DesmondLouis ,

Sorry for the late reply, been on vacation and traveling.

I think the issue is with the adding of the Facade. I had made a mistake in the README file (which ive updated now). It should be added to the aliases as follows

`'Language' => 'aharen\Language\Facades\Language::class',`

Cheers
